name: movie_app
description: A Movie App using TMDB API
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.1.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.0
  shared_preferences: ^2.0.0
  connectivity_plus: ^6.1.3
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_cache_manager: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

# Hapus atau comment bagian ini
# flutter:
#   fonts:
#     - family: Roboto
#       fonts:
#         - asset: assets/fonts/Roboto-Regular.ttf
#         - asset: assets/fonts/Roboto-Bold.ttf
#           weight: 700
